@startuml
enum nuru.IO.GlyphMode {
  None = 0
  ASCII = 1
  Unicode = 2
  PaletteFile = 129
}
enum nuru.IO.ColorMode {
  None = 0
  ANSI4 = 1
  ANSI8 = 2
  PaletteFile = 130
}
enum nuru.IO.MetaMode {
  None = 0
  UInt8 = 1
  UInt16 = 2
}
class nuru.IO.ImageFileCell {
  +Char : char
  +Fore : byte
  +Back : byte
  +Meta : ushort
}
class nuru.IO.ImageFile {
  +const Signature = "NURUIMG"
  +const Version = 1
  +GlyphMode
  +ColorMode
  +MetaMode
  +Width
  +Height
  +KeyChar
  +KeyFore
  +KeyBack
  +GlyphPalette
  +ColorPalette
  -cells

  +GetCell(x, y)
  +GetChar(x, y)
  +GetFore(x, y)
  +GetBack(x, y)
  +GetMeta(x, y)

  +SetCell(x, y, value)
  +SetChar(x, y, value)
  +SetFore(x, y, value)
  +SetBack(x, y, value)
  +SetMeta(x, y, value)

  +ToStream(formatWriter)
  +ToStream(stream)
  +ToFile(path)

  +static FromStream(formatReader)
  +static FromStream(stream)
  +static FromFile(path)
}

nuru.IO.GlyphMode --* "1" nuru.IO.ImageFile
nuru.IO.ColorMode --* "1" nuru.IO.ImageFile
nuru.IO.MetaMode --* "1" nuru.IO.ImageFile
nuru.IO.ImageFileCell --* "*" nuru.IO.ImageFile
@enduml