@startuml
class nuru.Image {
  +Image(imageFile, paletteProvider)
  +GetChar(x, y)
  +GetANSI(x, y)
  +GetRGB(x, y)
  +GetMeta(x, y)
  +IsKey(x, y)
}

class nuru.IO.ImageFile

class nuru.IO.PaletteFile

interface nuru.IO.IPaletteFileProvider {
  +GetGlyphFile(name) : PaletteFile
  +GetColorFile(name) : PaletteFile
}

nuru.IO.IPaletteFileProvider -[dashed]-> nuru.IO.PaletteFile
nuru.Image -[dashed]-> nuru.IO.ImageFile
nuru.Image -[dashed]-> nuru.IO.IPaletteFileProvider

note right of nuru.Image::"IsKey(x, y)"
  Useful for skipping rendering 
  character on key ch, fg or bg
end note
@enduml